# -*- coding: utf-8 -*-
"""TFG_Business_Analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13KCXNUcX_AnsU02dGBJgH9Vj-GyNxaU3
"""

# =========================================================
# ANÁLISIS EXPLORATORIO (EDA) - BGP
# =========================================================

# ---- carga y configuración ----
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from scipy import stats

from google.colab import drive
drive.mount('/content/drive')

RUTA      = '/content/drive/MyDrive/datos_limpios/bgp_diario_limpio.xlsx'
RUTA_FIGS = '/content/drive/MyDrive/datos_limpios/'

df = pd.read_excel(RUTA)
df['fecha']      = pd.to_datetime(df['fecha'])
df['mes']        = df['fecha'].dt.to_period('M')
df['dia_sem']    = df['fecha'].dt.dayofweek          # 0=Lun ... 4=Vie
df['dia_nombre'] = df['fecha'].dt.day_name()

# Eliminar los 3 sábados con alertadas=0
df = df[df['alertadas'] > 0].reset_index(drop=True)

df_n = df[df['tipo_cola'] == 'Normal'].copy()
df_u = df[df['tipo_cola'] == 'Urgente'].copy()

C_TIPO = {'Normal': '#2196F3', 'Urgente': '#F44336'}
C_PROV = {'Proveedor_A': '#E65100', 'Proveedor_B': '#6A1B9A'}
C_COLA = {
    'CMP_COV_BGP_ESSD8401':          '#E65100',
    'CMP_COV_BGPURGENCIAS_ESSD8401': '#FF7043',
    'CMP_MKT_BGP_ESSD8401':          '#6A1B9A',
    'CMP_MKT_BGPURGENCIAS_ESSD8401': '#AB47BC',
}
NOM_COLA = {
    'CMP_COV_BGP_ESSD8401':          'PA Normal',
    'CMP_COV_BGPURGENCIAS_ESSD8401': 'PA Urgente',
    'CMP_MKT_BGP_ESSD8401':          'PB Normal',
    'CMP_MKT_BGPURGENCIAS_ESSD8401': 'PB Urgente',
}

sns.set_theme(style='whitegrid', font_scale=1.05)
print(f"Dataset: {df.shape[0]} registros x {df.shape[1]} columnas")
print(f"Normales: {len(df_n)} | Urgentes: {len(df_u)}")
print(f"Periodo: {df['fecha'].min().date()} - {df['fecha'].max().date()}")

# ----antes vs después de la limpieza ----
df_antes   = pd.read_excel(RUTA)
df_antes['fecha'] = pd.to_datetime(df_antes['fecha'])
df_despues = df_antes[df_antes['alertadas'] > 0].copy()

print(f"Registros antes: {len(df_antes)} | despues: {len(df_despues)} | eliminados: {len(df_antes)-len(df_despues)}")

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
comparativas = [
    ('alertadas',                    'Alertadas / día'),
    ('tasa_abandono_pct',            'Tasa abandono (%)'),
    ('Ocupado_GestionBackOffice_min','BackOffice (min)'),
]
for col_i, (var, etiq) in enumerate(comparativas):
    for row_i, (dataset, label, color) in enumerate([
        (df_antes,   'Antes limpieza',   '#EF5350'),
        (df_despues, 'Despues limpieza', '#42A5F5'),
    ]):
        ax   = axes[row_i][col_i]
        data = dataset[var].dropna()
        ax.hist(data, bins=35, color=color, alpha=0.75, edgecolor='white')
        ax.axvline(data.mean(),   color='black',  ls='--', lw=1.3, label=f'Media: {data.mean():.2f}')
        ax.axvline(data.median(), color='orange', ls=':',  lw=1.3, label=f'Mediana: {data.median():.2f}')
        ax.set_title(f'{etiq}\n{label}  (n={len(data)})', fontweight='bold', fontsize=9)
        ax.set_xlabel(etiq, fontsize=8); ax.set_ylabel('Frecuencia', fontsize=8)
        ax.legend(fontsize=7.5)
fig.suptitle('Comparativa antes vs despues - limpieza del dataset', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(RUTA_FIGS + '00_antes_despues_limpieza.png', dpi=150, bbox_inches='tight')
plt.show()

# ---- tratamiento del outlier de BackOffice (acotación al P99) ----
tope_back = df['Ocupado_GestionBackOffice_min'].quantile(0.99)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
for ax, datos, titulo, color in zip(
    axes,
    [df['Ocupado_GestionBackOffice_min'],
     df['Ocupado_GestionBackOffice_min'].clip(upper=tope_back)],
    [f'Antes (max {df["Ocupado_GestionBackOffice_min"].max():.0f} min)',
     f'Despues de acotar al P99 (max {tope_back:.0f} min)'],
    ['#EF5350', '#42A5F5']):
    ax.hist(datos, bins=40, color=color, alpha=0.75, edgecolor='white')
    ax.axvline(datos.mean(), color='black', ls='--', lw=1.3, label=f'Media: {datos.mean():.0f}')
    ax.set_title(f'BackOffice (min)\n{titulo}', fontweight='bold')
    ax.set_xlabel('Minutos'); ax.set_ylabel('Frecuencia'); ax.legend()
fig.suptitle('Tratamiento de outliers - Ocupado_GestionBackOffice_min', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig(RUTA_FIGS + '00b_outliers_backoffice.png', dpi=150, bbox_inches='tight')
plt.show()

# Aplicar la acotación al dataset de trabajo
df['Ocupado_GestionBackOffice_min'] = df['Ocupado_GestionBackOffice_min'].clip(upper=tope_back)

# ---- estadísticos descriptivos ----
VARS_NUM = [
    'alertadas','respondidas','manejadas','no_contestadas','salientes',
    'n_gestores','llamadas_por_gestor',
    'tasa_abandono_pct','TMO_min','ASA_min','ACW_min',
    'tiempoManejo_min','tiempoConversacion_Entrantes_min',
    'tiempoDespuesTrabajo_min','tiempoAlertado_min',
    'EnPlataforma_min','Ocupado_GestionBackOffice_min','Disponible_min'
]

for nombre, subset in [('Dataset completo', df),
                       ('Colas Normales',   df_n),
                       ('Colas Urgentes',   df_u)]:
    t = subset[VARS_NUM].agg(['mean','median','std','min','max','skew']).T
    t.columns = ['Media','Mediana','Desv.Tipica','Minimo','Maximo','Asimetria']
    t['Curtosis'] = subset[VARS_NUM].apply(lambda x: x.kurt())
    print(f"\n{nombre} ({len(subset)} registros)")
    print(t.round(3).to_string())

# ---- tabla visual de KPIs por cola ----
VARS_T = ['alertadas','tasa_abandono_pct','TMO_min','ASA_min',
          'llamadas_por_gestor','n_gestores']

resumen = df.groupby('cola_nombre')[VARS_T].agg(['mean','std','min','max']).round(2)
resumen.index = [NOM_COLA[c] for c in resumen.index]

fig, ax = plt.subplots(figsize=(18, 3.5))
ax.axis('off')
cols_hdr = [f"{v}\n{s}" for v in ['Alertadas','Abandono(%)','TMO(min)',
                                  'ASA(min)','Llam/gestor','Gestores']
            for s in ['Media','Std','Min','Max']]
tabla = ax.table(cellText=resumen.values, rowLabels=resumen.index,
                 colLabels=cols_hdr, cellLoc='center', loc='center')
tabla.auto_set_font_size(False); tabla.set_fontsize(7.5); tabla.scale(1, 2)
for (r, c), cell in tabla.get_celld().items():
    if r == 0:
        cell.set_facecolor('#37474F'); cell.set_text_props(color='white', fontweight='bold')
    elif c == -1:
        cell.set_facecolor('#ECEFF1'); cell.set_text_props(fontweight='bold')
plt.title('Estadisticos descriptivos - KPIs principales por cola', fontweight='bold', pad=15)
plt.tight_layout()
plt.savefig(RUTA_FIGS+'01_tabla_estadisticos.png', dpi=150, bbox_inches='tight')
plt.show()

# Jornadas con abandono extremo
print(df[df['tasa_abandono_pct'] > 12][
    ['fecha','cola_nombre','alertadas','no_contestadas','tasa_abandono_pct','n_gestores']
].to_string())

# ---- histogramas con KDE ----
VARS_H = ['alertadas','tasa_abandono_pct','TMO_min','ASA_min']
ETIQ_H = ['Alertadas / dia','Tasa abandono (%)','TMO (min)','ASA (min)']

fig, axes = plt.subplots(2, 4, figsize=(18, 9))
for col_i, (var, etiq) in enumerate(zip(VARS_H, ETIQ_H)):
    for row_i, (tipo, color) in enumerate(C_TIPO.items()):
        ax   = axes[row_i][col_i]
        data = df[df['tipo_cola'] == tipo][var].dropna()
        ax.hist(data, bins=30, density=True, alpha=0.45, color=color, edgecolor='white')
        kde_x = np.linspace(data.min(), data.max(), 300)
        ax.plot(kde_x, stats.gaussian_kde(data)(kde_x), color=color, lw=2)
        ax.axvline(data.mean(),   color='black',      ls='--', lw=1.3, label=f'Media {data.mean():.2f}')
        ax.axvline(data.median(), color='darkorange', ls=':',  lw=1.3, label=f'Mediana {data.median():.2f}')
        if var == 'tasa_abandono_pct':
            ax.axvline(5.5, color='red', lw=1.8, label='Target 5.5%')
        if var == 'alertadas' and tipo == 'Normal':
            ax.annotate('Bimodalidad:\nPA (~600) vs PB (~1200)',
                        xy=(900, ax.get_ylim()[1]*0.7 if ax.get_ylim()[1] > 0 else 0.001),
                        fontsize=7.5, color='navy',
                        bbox=dict(boxstyle='round,pad=0.3', facecolor='lightyellow', alpha=0.85))
        ax.set_title(f'{etiq}\n{tipo}  |  asim={data.skew():.2f}', fontweight='bold', fontsize=9)
        ax.set_xlabel(etiq, fontsize=8); ax.set_ylabel('Densidad', fontsize=8)
        ax.legend(fontsize=7)
fig.suptitle('Distribuciones de KPIs principales - Normal vs Urgente', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(RUTA_FIGS+'02_histogramas.png', dpi=150, bbox_inches='tight')
plt.show()

# ---- boxplots por proveedor y tipo ----
fig, axes = plt.subplots(2, 4, figsize=(18, 10))
for col_i, (var, etiq) in enumerate(zip(VARS_H, ETIQ_H)):
    for row_i, (tipo, color) in enumerate(C_TIPO.items()):
        ax     = axes[row_i][col_i]
        df_tmp = df[df['tipo_cola'] == tipo]
        sns.boxplot(data=df_tmp, x='proveedor', y=var,
                    palette=C_PROV, width=0.45, linewidth=1.2,
                    flierprops=dict(marker='o', markersize=3.5, alpha=0.45), ax=ax)
        if var == 'tasa_abandono_pct':
            ax.axhline(5.5, color='red', ls='--', lw=1.4, label='Target 5.5%')
            ax.legend(fontsize=7.5)
        for j, prov in enumerate(['Proveedor_A','Proveedor_B']):
            d = df_tmp[df_tmp['proveedor']==prov][var].dropna()
            q1, q3 = d.quantile(.25), d.quantile(.75)
            n_out  = ((d < q1-1.5*(q3-q1)) | (d > q3+1.5*(q3-q1))).sum()
            ax.text(j, ax.get_ylim()[0], f'out={n_out}', ha='center', fontsize=7, color='gray')
        ax.set_title(f'{etiq}\n{tipo}', fontweight='bold', fontsize=9)
        ax.set_xlabel(''); ax.set_ylabel(etiq, fontsize=8)
        ax.set_xticklabels(['Prov_A','Prov_B'], fontsize=8)
fig.suptitle('Boxplots de KPIs - Proveedor x Tipo de cola', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(RUTA_FIGS+'03_boxplots.png', dpi=150, bbox_inches='tight')
plt.show()

# ---- series temporales mensuales ----
VARS_ST = ['alertadas','tasa_abandono_pct','TMO_min','ASA_min']
ETIQ_ST = ['Alertadas totales / mes','Tasa abandono media (%)','TMO medio (min)','ASA media (min)']
AGG_ST  = {'alertadas':'sum','tasa_abandono_pct':'mean','TMO_min':'mean','ASA_min':'mean'}
EVENTOS = {'2025-08': 'Verano', '2025-12': 'Navidades'}

fig, axes = plt.subplots(2, 2, figsize=(16, 10))
axes = axes.flatten()
for i, (var, etiq) in enumerate(zip(VARS_ST, ETIQ_ST)):
    for cola, color in C_COLA.items():
        tmp = (df[df['cola_nombre']==cola].groupby('mes')[var].agg(AGG_ST[var]).reset_index())
        tmp['mes_dt'] = tmp['mes'].dt.to_timestamp()
        axes[i].plot(tmp['mes_dt'], tmp[var], marker='o', color=color, lw=2, label=NOM_COLA[cola])
    if var == 'tasa_abandono_pct':
        axes[i].axhline(5.5, color='red', ls='--', lw=1.5, label='Target 5.5%')
    for mes_str, label in EVENTOS.items():
        dt = pd.Timestamp(mes_str)
        axes[i].axvline(dt, color='gray', ls=':', lw=1, alpha=0.7)
        axes[i].text(dt, axes[i].get_ylim()[1]*0.95 if axes[i].get_ylim()[1] > 0 else 1,
                     label, fontsize=7.5, color='gray', rotation=90, va='top')
    axes[i].set_title(etiq, fontweight='bold')
    axes[i].set_xlabel('Mes'); axes[i].set_ylabel(etiq)
    axes[i].legend(fontsize=8); axes[i].tick_params(axis='x', rotation=45)
fig.suptitle('Evolucion mensual - las 4 colas BGP', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.savefig(RUTA_FIGS+'04_series_temporales.png', dpi=150, bbox_inches='tight')
plt.show()

# ---- volumen diario con media móvil 7 días ----
fig, axes = plt.subplots(2, 2, figsize=(18, 10))
axes = axes.flatten()
for i, (cola, color) in enumerate(C_COLA.items()):
    tmp = df[df['cola_nombre']==cola].sort_values('fecha')
    mm7 = tmp['alertadas'].rolling(7, min_periods=1).mean()
    axes[i].fill_between(tmp['fecha'], tmp['alertadas'], alpha=0.2, color=color)
    axes[i].plot(tmp['fecha'], tmp['alertadas'], alpha=0.35, color=color, lw=0.8)
    axes[i].plot(tmp['fecha'], mm7, color=color, lw=2.2, label='Media movil 7d')
    axes[i].set_title(NOM_COLA[cola], fontweight='bold')
    axes[i].set_xlabel('Fecha'); axes[i].set_ylabel('Alertadas / dia')
    axes[i].legend(); axes[i].tick_params(axis='x', rotation=30)
fig.suptitle('Volumen diario de llamadas con media movil 7 dias', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.savefig(RUTA_FIGS+'05_volumen_mm7.png', dpi=150, bbox_inches='tight')
plt.show()

# ---- patrón semanal ----
DIAS = ['Lun','Mar','Mie','Jue','Vie']

fig, axes = plt.subplots(1, 2, figsize=(14, 6))
for ax, tipo in zip(axes, ['Normal','Urgente']):
    tmp = (df[(df['tipo_cola']==tipo) & (df['dia_sem'] < 5)]
           .groupby(['dia_sem','proveedor'])['alertadas'].mean().reset_index())
    for prov, color in C_PROV.items():
        sub = tmp[tmp['proveedor']==prov]
        offset = -0.2 if prov=='Proveedor_A' else 0.2
        bars = ax.bar([d+offset for d in sub['dia_sem']], sub['alertadas'],
                      width=0.38, color=color, alpha=0.82, label=prov)
        ax.bar_label(bars, fmt='%.0f', padding=2, fontsize=7.5)
    ax.set_xticks(range(5)); ax.set_xticklabels(DIAS)
    ax.set_title(f'Llamadas medias por dia - {tipo}', fontweight='bold')
    ax.set_ylabel('Alertadas medias / dia'); ax.legend()
fig.suptitle('Patron semanal de volumen de llamadas', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.savefig(RUTA_FIGS+'06_patron_semanal.png', dpi=150, bbox_inches='tight')
plt.show()

# ---- matrices de correlación ----
VARS_C = ['alertadas','n_gestores','llamadas_por_gestor','salientes',
          'tasa_abandono_pct','TMO_min','ASA_min','ACW_min',
          'tiempoConversacion_Entrantes_min','tiempoDespuesTrabajo_min',
          'EnPlataforma_min','Disponible_min']

fig, axes = plt.subplots(1, 2, figsize=(18, 8))
for ax, tipo in zip(axes, ['Normal','Urgente']):
    corr = df[df['tipo_cola']==tipo][VARS_C].corr()
    mask = np.triu(np.ones_like(corr, dtype=bool))
    sns.heatmap(corr, mask=mask, annot=True, fmt='.2f', cmap='RdBu_r',
                vmin=-1, vmax=1, linewidths=0.4, ax=ax, annot_kws={'size':7.5})
    ax.set_title(f'Correlaciones - {tipo}', fontweight='bold', fontsize=12)
    ax.tick_params(axis='x', rotation=45, labelsize=8)
    ax.tick_params(axis='y', rotation=0,  labelsize=8)
fig.suptitle('Matrices de correlacion por tipo de cola', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.savefig(RUTA_FIGS+'07_correlacion_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

# ---- correlación con la tasa de abandono ----
fig, axes = plt.subplots(1, 2, figsize=(14, 6))
for ax, tipo in zip(axes, ['Normal','Urgente']):
    corr_ab = (df[df['tipo_cola']==tipo][VARS_C].corr()['tasa_abandono_pct']
               .drop('tasa_abandono_pct').sort_values())
    colors = ['#F44336' if v > 0 else '#2196F3' for v in corr_ab]
    ax.barh(corr_ab.index, corr_ab.values, color=colors, alpha=0.8)
    ax.axvline(0, color='black', lw=0.8)
    ax.axvline( 0.3, color='gray', ls='--', lw=0.8, alpha=0.6)
    ax.axvline(-0.3, color='gray', ls='--', lw=0.8, alpha=0.6)
    ax.set_title(f'Correlacion con abandono - {tipo}', fontweight='bold')
    ax.set_xlabel('Correlacion de Pearson'); ax.tick_params(axis='y', labelsize=9)
fig.suptitle('Que variables se correlacionan con la tasa de abandono', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(RUTA_FIGS+'08_corr_abandono.png', dpi=150, bbox_inches='tight')
plt.show()

# ---- scatter carga vs abandono ----
fig, axes = plt.subplots(1, 2, figsize=(14, 6))
for ax, tipo in zip(axes, ['Normal','Urgente']):
    df_t = df[df['tipo_cola']==tipo]
    for cola, color in C_COLA.items():
        sub = df_t[df_t['cola_nombre']==cola]
        if len(sub)==0: continue
        ax.scatter(sub['llamadas_por_gestor'], sub['tasa_abandono_pct'],
                   c=color, alpha=0.4, s=28, label=NOM_COLA[cola], edgecolors='none')
    x = df_t['llamadas_por_gestor'].dropna()
    y = df_t['tasa_abandono_pct'].loc[x.index]
    m, b = np.polyfit(x, y, 1)
    r, _ = stats.pearsonr(x, y)
    ax.plot(sorted(x), [m*xi+b for xi in sorted(x)], color='black', lw=1.8, ls='--', label=f'Tendencia  r={r:.2f}')
    ax.axhline(5.5, color='red', ls=':', lw=1.3, label='Target 5.5%')
    ax.set_title(f'Carga vs abandono - {tipo}', fontweight='bold')
    ax.set_xlabel('Llamadas por gestor'); ax.set_ylabel('Tasa abandono (%)')
    ax.legend(fontsize=8)
fig.suptitle('Relacion carga de trabajo vs tasa de abandono', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(RUTA_FIGS+'10_scatter_carga_abandono.png', dpi=150, bbox_inches='tight')
plt.show()

# ---- scatter ASA vs abandono ----
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Relacion tiempo de espera (ASA) vs tasa de abandono', fontsize=14, fontweight='bold')
colores = {
    ('Normal',  'Proveedor_A'): '#FF8C69',
    ('Normal',  'Proveedor_B'): '#9B59B6',
    ('Urgente', 'Proveedor_A'): '#FF6347',
    ('Urgente', 'Proveedor_B'): '#6A0DAD',
}
for ax, tipo in zip(axes, ['Normal', 'Urgente']):
    df_t = df[df['tipo_cola'] == tipo].copy()
    for prov in ['Proveedor_A', 'Proveedor_B']:
        sub = df_t[df_t['proveedor'] == prov]
        ax.scatter(sub['ASA_min'], sub['tasa_abandono_pct'],
                   color=colores[(tipo, prov)], alpha=0.45, s=28, label=prov.replace('_', ' '))
    x = df_t['ASA_min'].values
    y = df_t['tasa_abandono_pct'].values
    mask = np.isfinite(x) & np.isfinite(y)
    slope, intercept, r, p, _ = stats.linregress(x[mask], y[mask])
    x_line = np.linspace(x[mask].min(), x[mask].max(), 100)
    ax.plot(x_line, slope * x_line + intercept, 'k--', lw=1.6, label=f'Tendencia r={r:.2f}')
    ax.axhline(5.5, color='red', linestyle=':', lw=1.4, label='Target 5,5%')
    ax.set_title(f'ASA vs abandono - {tipo}', fontsize=11)
    ax.set_xlabel('ASA media (min)'); ax.set_ylabel('Tasa abandono (%)')
    ax.legend(fontsize=8); ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig(RUTA_FIGS+'10b_scatter_asa_abandono.png', dpi=150, bbox_inches='tight')
plt.show()

# ---- contraste ADF de estacionariedad ----
from statsmodels.tsa.stattools import adfuller

adf_resultados = {}
for cola, grupo in df.groupby('cola_nombre'):
    serie = grupo.sort_values('fecha')['tasa_abandono_pct'].dropna()
    stat, pval, _, _, _, _ = adfuller(serie, autolag='AIC')
    adf_resultados[cola] = {'ADF stat': round(stat, 3), 'p-valor': round(pval, 4)}

adf_df = pd.DataFrame(adf_resultados).T
print(adf_df)
rechaza = (adf_df['p-valor'] < 0.05).all()
print(f"\nTodas las series rechazan raiz unitaria (p<0,05): {'SI' if rechaza else 'NO'}")

# ---- tramos de carga e incumplimiento del SLA ----
# Tramos de llamadas/gestor y % de dias que incumplen el SLA
df_normal  = df[df['tipo_cola'] == 'Normal'].copy()
df_urgente = df[df['tipo_cola'] == 'Urgente'].copy()

bins_n = [0, 25, 35, 45, 55, 200]
labs_n = ['<25', '25-35', '35-45', '45-55', '>55']
df_normal['tramo_carga'] = pd.cut(df_normal['llamadas_por_gestor'], bins=bins_n, labels=labs_n)

resumen_normal = (df_normal.groupby('tramo_carga', observed=True)
                  .apply(lambda g: pd.Series({
                      'n_dias': len(g),
                      'pct_incumple': round((g['tasa_abandono_pct'] > 5.5).mean() * 100, 1),
                      'abandono_medio': round(g['tasa_abandono_pct'].mean(), 2)
                  })).reset_index())
print("Colas Normales")
print(resumen_normal.to_string(index=False))

bins_u = [0, 5, 8, 12, 25, 200]
labs_u = ['<5', '5-8', '8-12', '12-25', '>25']
df_urgente['tramo_carga'] = pd.cut(df_urgente['llamadas_por_gestor'], bins=bins_u, labels=labs_u)

resumen_urgente = (df_urgente.groupby('tramo_carga', observed=True)
                   .apply(lambda g: pd.Series({
                       'n_dias': len(g),
                       'pct_incumple': round((g['tasa_abandono_pct'] > 5.5).mean() * 100, 1),
                       'abandono_medio': round(g['tasa_abandono_pct'].mean(), 2)
                   })).reset_index())
print("\nColas Urgentes")
print(resumen_urgente.to_string(index=False))

=========================================================
# ANÁLISIS DEL DATO - BGP
# =========================================================

# ---- Celda 1: imports y carga ----
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive', force_remount=False)

RUTA      = '/content/drive/MyDrive/datos_limpios/bgp_diario_limpio.xlsx'
RUTA_FIGS = '/content/drive/MyDrive/datos_limpios/'
RANDOM_STATE = 42

df = pd.read_excel(RUTA)
df['fecha'] = pd.to_datetime(df['fecha'])
print(f"Dataset: {df.shape[0]} filas x {df.shape[1]} columnas")
print(f"Periodo: {df['fecha'].min().date()} - {df['fecha'].max().date()}")

# ---- Celda 2: exclusión de variables (anti-leakage) ----
EXCLUIR = [
    'no_contestadas',                     # determina directamente el target
    'respondidas',                        # alertadas - no_contestadas
    'manejadas',                          # solapamiento con respondidas
    'tiempoManejo_min',                   # TMO_min x volumen
    'tiempoConversacion_Entrantes_min',   # componente de TMO_min
    'tiempoDespuesTrabajo_min',           # ACW_min x volumen
    'tiempoAlertado_min',                 # ASA_min x volumen
    'cola_nombre',                        # redundante con proveedor + tipo_cola
]
df_modelo = df.drop(columns=EXCLUIR)
print(f"Variables tras exclusiones: {df_modelo.shape[1]}")

# ---- Celda 3: feature engineering ----
df_modelo['dia_semana'] = df_modelo['fecha'].dt.dayofweek
df_modelo['mes']        = df_modelo['fecha'].dt.month

# Codificación cíclica de las variables temporales
df_modelo['dia_semana_sin'] = np.sin(2 * np.pi * df_modelo['dia_semana'] / 7)
df_modelo['dia_semana_cos'] = np.cos(2 * np.pi * df_modelo['dia_semana'] / 7)
df_modelo['mes_sin']        = np.sin(2 * np.pi * df_modelo['mes'] / 12)
df_modelo['mes_cos']        = np.cos(2 * np.pi * df_modelo['mes'] / 12)

# Codificación de categóricas
df_modelo['proveedor_enc'] = df_modelo['proveedor'].map({'Proveedor_A': 0, 'Proveedor_B': 1})
df_modelo['tipo_cola_enc'] = df_modelo['tipo_cola'].map({'Normal': 0, 'Urgente': 1})

# Target binario para la fase de clasificación
df_modelo['supera_target'] = (df_modelo['tasa_abandono_pct'] > 5.5).astype(int)

print(df_modelo['supera_target'].value_counts())
print(f"Tasa de incumplimiento: {df_modelo['supera_target'].mean():.1%}")

# ---- Celda 4: features, target y split temporal ----
FEATURES = [
    'alertadas', 'salientes', 'n_gestores', 'llamadas_por_gestor',
    'TMO_min', 'ASA_min', 'ACW_min',
    'EnPlataforma_min', 'Ocupado_GestionBackOffice_min', 'Disponible_min',
    'proveedor_enc', 'tipo_cola_enc',
    'dia_semana_sin', 'dia_semana_cos', 'mes_sin', 'mes_cos'
]
TARGET_REG = 'tasa_abandono_pct'
TARGET_CLF = 'supera_target'

FECHA_CORTE = '2025-12-31'
mask_train = df_modelo['fecha'] <= FECHA_CORTE
mask_test  = df_modelo['fecha'] >  FECHA_CORTE

X_train = df_modelo.loc[mask_train, FEATURES]
X_test  = df_modelo.loc[mask_test,  FEATURES]
y_train_reg = df_modelo.loc[mask_train, TARGET_REG]
y_test_reg  = df_modelo.loc[mask_test,  TARGET_REG]
y_train_clf = df_modelo.loc[mask_train, TARGET_CLF]
y_test_clf  = df_modelo.loc[mask_test,  TARGET_CLF]

print(f"TRAIN: {X_train.shape[0]} obs ({df_modelo.loc[mask_train,'fecha'].min().date()} - {df_modelo.loc[mask_train,'fecha'].max().date()})")
print(f"TEST:  {X_test.shape[0]} obs ({df_modelo.loc[mask_test,'fecha'].min().date()} - {df_modelo.loc[mask_test,'fecha'].max().date()})")
print(f"Incumplimiento train: {y_train_clf.mean():.1%} | test: {y_test_clf.mean():.1%}")

# Escalado (fit solo en train)
scaler = StandardScaler()
X_train_sc = pd.DataFrame(scaler.fit_transform(X_train), columns=FEATURES, index=X_train.index)
X_test_sc  = pd.DataFrame(scaler.transform(X_test),      columns=FEATURES, index=X_test.index)
print(f"Media train (~0): {X_train_sc.mean().mean():.6f} | Std train (~1): {X_train_sc.std().mean():.4f}")

# ---- Celda 5: caracterización del objetivo y partición ----
# Distribución de la tasa de abandono por tipo de cola
fig, ax = plt.subplots(figsize=(8, 5))
for tipo, color in [('Normal', '#2196F3'), ('Urgente', '#F44336')]:
    d = df_modelo[df_modelo['tipo_cola'] == tipo]['tasa_abandono_pct']
    ax.hist(d, bins=30, density=True, alpha=0.5, color=color, label=tipo)
    ax.axvline(d.mean(), color=color, ls='--', lw=1.3)
ax.axvline(5.5, color='red', lw=1.8, label='Umbral SLA (5.5%)')
ax.set_xlabel('tasa_abandono_pct (%)'); ax.set_ylabel('Densidad')
ax.set_title('Distribucion de la tasa de abandono por tipo de cola', fontweight='bold')
ax.legend()
plt.tight_layout()
plt.savefig(RUTA_FIGS + 'dato_dist_abandono_tipo.png', dpi=150, bbox_inches='tight')
plt.show()

# Partición temporal train / test
fig, ax = plt.subplots(figsize=(12, 4))
ax.scatter(df_modelo.loc[mask_train, 'fecha'], df_modelo.loc[mask_train, 'tasa_abandono_pct'],
           s=10, alpha=0.5, color='steelblue', label=f'Train ({mask_train.sum()})')
ax.scatter(df_modelo.loc[mask_test, 'fecha'], df_modelo.loc[mask_test, 'tasa_abandono_pct'],
           s=10, alpha=0.5, color='darkorange', label=f'Test ({mask_test.sum()})')
ax.axvline(pd.Timestamp(FECHA_CORTE), color='red', ls='--', lw=1.5, label='Corte 31-12-2025')
ax.axhline(5.5, color='gray', ls=':', lw=1)
ax.set_xlabel('Fecha'); ax.set_ylabel('tasa_abandono_pct (%)')
ax.set_title('Particion temporal del conjunto de datos', fontweight='bold')
ax.legend()
plt.tight_layout()
plt.savefig(RUTA_FIGS + 'dato_particion_temporal.png', dpi=150, bbox_inches='tight')
plt.show()

# =========================================================
# FASE 1: K-MEANS
# =========================================================
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA

COLORES = ['steelblue', 'darkorange', 'seagreen', 'firebrick', 'mediumpurple']

# ---- Celda 6: K-Means iteración 1 (todas las variables) ----
K_RANGE = range(2, 11)
inercias, silhouettes = [], []
for k in K_RANGE:
    km = KMeans(n_clusters=k, random_state=RANDOM_STATE, n_init=10)
    labels = km.fit_predict(X_train_sc)
    inercias.append(km.inertia_)
    silhouettes.append(silhouette_score(X_train_sc, labels))

fig, axes = plt.subplots(1, 2, figsize=(13, 4))
axes[0].plot(K_RANGE, inercias, marker='o', color='steelblue', lw=2)
axes[0].set_xlabel('Numero de clusters (k)'); axes[0].set_ylabel('Inercia (WCSS)')
axes[0].set_title('Metodo del codo', fontweight='bold'); axes[0].grid(alpha=0.3)
axes[1].plot(K_RANGE, silhouettes, marker='s', color='darkorange', lw=2)
axes[1].set_xlabel('Numero de clusters (k)'); axes[1].set_ylabel('Silhouette score')
axes[1].set_title('Silhouette por k', fontweight='bold'); axes[1].grid(alpha=0.3)
plt.tight_layout()
plt.savefig(RUTA_FIGS + '11_kmeans_seleccion_k.png', dpi=150, bbox_inches='tight')
plt.show()

for k, in_, si_ in zip(K_RANGE, inercias, silhouettes):
    print(f"k={k}  inercia={in_:10.1f}  silhouette={si_:.4f}")

# k=3 segun la interpretacion de regimenes operativos
K_OPTIMO = 3
print(f"\nSilhouette en k={K_OPTIMO}: {silhouettes[K_OPTIMO-2]:.4f}")

km_final = KMeans(n_clusters=K_OPTIMO, random_state=RANDOM_STATE, n_init=10)
cluster_train = km_final.fit_predict(X_train_sc)
df_modelo.loc[mask_train, 'cluster'] = cluster_train
df_modelo.loc[mask_test,  'cluster'] = km_final.predict(X_test_sc)
df_modelo['cluster'] = df_modelo['cluster'].astype(int)

# ---- Celda 7: PCA 2D iteración 1 ----
pca = PCA(n_components=2, random_state=RANDOM_STATE)
X_pca = pca.fit_transform(X_train_sc)
var = pca.explained_variance_ratio_
print(f"Varianza PC1={var[0]:.1%}  PC2={var[1]:.1%}  Total={sum(var):.1%}")

fig, ax = plt.subplots(figsize=(9, 6))
for c in range(K_OPTIMO):
    m = cluster_train == c
    ax.scatter(X_pca[m, 0], X_pca[m, 1], c=COLORES[c], label=f'Cluster {c}',
               alpha=0.6, s=40, edgecolors='white', linewidth=0.3)
ax.set_xlabel(f'PC1 ({var[0]:.1%})'); ax.set_ylabel(f'PC2 ({var[1]:.1%})')
ax.set_title(f'Proyeccion PCA 2D - todas las variables (k={K_OPTIMO})', fontweight='bold')
ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(RUTA_FIGS + '12_kmeans_pca2d.png', dpi=150, bbox_inches='tight')
plt.show()

# Perfil operativo por cluster
VARS_PERFIL = ['tasa_abandono_pct', 'llamadas_por_gestor', 'ASA_min', 'TMO_min',
               'ACW_min', 'n_gestores', 'alertadas', 'supera_target']
perfil = df_modelo[mask_train].groupby('cluster')[VARS_PERFIL].mean().round(2)
print(perfil.to_string())
print("\nComposicion por tipo de cola:")
print(pd.crosstab(df_modelo.loc[mask_train, 'cluster'], df_modelo.loc[mask_train, 'tipo_cola'], normalize='index').round(2))

# ---- Celda 8: K-Means iteración 2 (solo KPIs operativos) ----
FEATURES_KM2 = ['llamadas_por_gestor', 'TMO_min', 'ASA_min', 'ACW_min']
scaler_km2 = StandardScaler()
X_km2_train = scaler_km2.fit_transform(X_train[FEATURES_KM2])

inercias2, silhouettes2 = [], []
for k in K_RANGE:
    km = KMeans(n_clusters=k, random_state=RANDOM_STATE, n_init=10)
    labels = km.fit_predict(X_km2_train)
    inercias2.append(km.inertia_)
    silhouettes2.append(silhouette_score(X_km2_train, labels))

fig, axes = plt.subplots(1, 2, figsize=(13, 4))
axes[0].plot(K_RANGE, inercias2, marker='o', color='steelblue', lw=2)
axes[0].set_xlabel('Numero de clusters (k)'); axes[0].set_ylabel('Inercia (WCSS)')
axes[0].set_title('Metodo del codo - KPIs operativos', fontweight='bold'); axes[0].grid(alpha=0.3)
axes[1].plot(K_RANGE, silhouettes2, marker='s', color='darkorange', lw=2)
axes[1].set_xlabel('Numero de clusters (k)'); axes[1].set_ylabel('Silhouette score')
axes[1].set_title('Silhouette por k - KPIs operativos', fontweight='bold'); axes[1].grid(alpha=0.3)
plt.tight_layout()
plt.savefig(RUTA_FIGS + '11b_kmeans2_seleccion_k.png', dpi=150, bbox_inches='tight')
plt.show()

for k, in_, si_ in zip(K_RANGE, inercias2, silhouettes2):
    print(f"k={k}  inercia={in_:8.1f}  silhouette={si_:.4f}")

K_OPTIMO2 = 3
print(f"\nSilhouette en k={K_OPTIMO2}: {silhouettes2[K_OPTIMO2-2]:.4f}")

km2_final = KMeans(n_clusters=K_OPTIMO2, random_state=RANDOM_STATE, n_init=10)
cluster2_train = km2_final.fit_predict(X_km2_train)
df_modelo.loc[mask_train, 'cluster2'] = cluster2_train
df_modelo.loc[mask_test,  'cluster2'] = km2_final.predict(scaler_km2.transform(X_test[FEATURES_KM2]))
df_modelo['cluster2'] = df_modelo['cluster2'].astype(int)

pca2 = PCA(n_components=2, random_state=RANDOM_STATE)
X_pca2 = pca2.fit_transform(X_km2_train)
var2 = pca2.explained_variance_ratio_
print(f"Varianza PC1={var2[0]:.1%}  PC2={var2[1]:.1%}  Total={sum(var2):.1%}")

fig, ax = plt.subplots(figsize=(9, 6))
for c in range(K_OPTIMO2):
    m = cluster2_train == c
    ax.scatter(X_pca2[m, 0], X_pca2[m, 1], c=COLORES[c], label=f'Cluster {c}',
               alpha=0.6, s=40, edgecolors='white', linewidth=0.3)
ax.set_xlabel(f'PC1 ({var2[0]:.1%})'); ax.set_ylabel(f'PC2 ({var2[1]:.1%})')
ax.set_title(f'Proyeccion PCA 2D - KPIs operativos (k={K_OPTIMO2})', fontweight='bold')
ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(RUTA_FIGS + '12b_kmeans2_pca2d.png', dpi=150, bbox_inches='tight')
plt.show()

VARS_PERFIL2 = ['tasa_abandono_pct', 'llamadas_por_gestor', 'ASA_min', 'TMO_min', 'ACW_min', 'supera_target']
perfil2 = df_modelo[mask_train].groupby('cluster2')[VARS_PERFIL2].mean().round(2)
print(perfil2.to_string())

# =========================================================
# FASE 2: REGRESIÓN
# =========================================================
from sklearn.linear_model import RidgeCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import TimeSeriesSplit, cross_validate
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from statsmodels.stats.outliers_influence import variance_inflation_factor
import xgboost as xgb
import shap

TSCV = TimeSeriesSplit(n_splits=5)

def metricas_regresion(y_true, y_pred, nombre=''):
    r2   = r2_score(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae  = mean_absolute_error(y_true, y_pred)
    if nombre:
        print(f"\n{nombre}: R2={r2:.4f}  RMSE={rmse:.4f}  MAE={mae:.4f}")
    return {'R2': r2, 'RMSE': rmse, 'MAE': mae}

# ---- Celda 9: diagnóstico de multicolinealidad (VIF) ----
vif_data = pd.DataFrame({
    'Feature': FEATURES,
    'VIF': [variance_inflation_factor(X_train_sc.values, i) for i in range(X_train_sc.shape[1])]
}).sort_values('VIF', ascending=False)
print(vif_data.to_string(index=False))
print("\nReferencia: VIF > 10 indica multicolinealidad severa")

# Gráfico de VIF en escala logarítmica
v = vif_data.sort_values('VIF')
colores_vif = ['firebrick' if x > 10 else 'darkorange' if x > 5 else 'steelblue' for x in v['VIF']]
fig, ax = plt.subplots(figsize=(9, 6))
ax.barh(v['Feature'], v['VIF'], color=colores_vif, alpha=0.85)
ax.set_xscale('log')
ax.axvline(10, color='red', ls='--', lw=1.2, label='VIF = 10 (critico)')
ax.axvline(5,  color='orange', ls='--', lw=1.2, label='VIF = 5 (moderado)')
ax.set_xlabel('VIF (escala log)')
ax.set_title('Factor de inflacion de la varianza por variable', fontweight='bold')
ax.legend(); ax.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.savefig(RUTA_FIGS + 'dato_vif.png', dpi=150, bbox_inches='tight')
plt.show()

# ---- Celda 10: Ridge ----
ridge = RidgeCV(alphas=np.logspace(-3, 3, 100), cv=TSCV)
ridge.fit(X_train_sc, y_train_reg)
print(f"Alpha optimo: {ridge.alpha_:.4f}")

y_pred_ridge = ridge.predict(X_test_sc)
res_ridge = metricas_regresion(y_test_reg, y_pred_ridge, 'Ridge - TEST')

coef_ridge = pd.DataFrame({'Feature': FEATURES, 'Coeficiente': ridge.coef_}).sort_values('Coeficiente', key=abs, ascending=False)
print(coef_ridge.to_string(index=False))

# ---- Celda 11: Random Forest regresor ----
rf = RandomForestRegressor(n_estimators=300, min_samples_leaf=5, max_features='sqrt',
                           random_state=RANDOM_STATE, n_jobs=-1)
rf.fit(X_train, y_train_reg)
y_pred_rf = rf.predict(X_test)
res_rf = metricas_regresion(y_test_reg, y_pred_rf, 'Random Forest - TEST')

imp_rf = pd.DataFrame({'Feature': FEATURES, 'Importancia': rf.feature_importances_}).sort_values('Importancia', ascending=False)
print(imp_rf.to_string(index=False))

# ---- Celda 12: XGBoost regresor ----
xgb_reg = xgb.XGBRegressor(n_estimators=500, learning_rate=0.05, max_depth=5,
                           subsample=0.8, colsample_bytree=0.8, reg_alpha=0.1, reg_lambda=1.0,
                           early_stopping_rounds=30, random_state=RANDOM_STATE,
                           eval_metric='rmse', verbosity=0)
splits = list(TSCV.split(X_train))
idx_tr, idx_val = splits[-1]
xgb_reg.fit(X_train.iloc[idx_tr], y_train_reg.iloc[idx_tr],
            eval_set=[(X_train.iloc[idx_val], y_train_reg.iloc[idx_val])], verbose=False)
print(f"XGBoost - arboles optimos: {xgb_reg.best_iteration}")
y_pred_xgb = xgb_reg.predict(X_test)
res_xgb = metricas_regresion(y_test_reg, y_pred_xgb, 'XGBoost - TEST')

# ---- Celda 13: comparativa de regresión + figuras ----
resultados = pd.DataFrame({
    'Modelo': ['Ridge', 'XGBoost', 'Random Forest'],
    'R2':   [res_ridge['R2'],   res_xgb['R2'],   res_rf['R2']],
    'RMSE': [res_ridge['RMSE'], res_xgb['RMSE'], res_rf['RMSE']],
    'MAE':  [res_ridge['MAE'],  res_xgb['MAE'],  res_rf['MAE']],
})
print(resultados.to_string(index=False))

modelos_pred = [('Ridge', y_pred_ridge, 'steelblue'),
                ('Random Forest', y_pred_rf, 'darkorange'),
                ('XGBoost', y_pred_xgb, 'seagreen')]

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
for ax, (nombre, y_pred, color) in zip(axes, modelos_pred):
    ax.scatter(y_test_reg, y_pred, alpha=0.4, s=20, color=color)
    lims = [min(y_test_reg.min(), y_pred.min()), max(y_test_reg.max(), y_pred.max())]
    ax.plot(lims, lims, 'r--', lw=1.5)
    ax.set_xlabel('Valor real (%)'); ax.set_ylabel('Valor predicho (%)')
    ax.set_title(nombre, fontweight='bold'); ax.grid(alpha=0.3)
fig.suptitle('Predicho vs real - modelos de regresion', fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig(RUTA_FIGS + '14_reg_predicho_vs_real.png', dpi=150, bbox_inches='tight')
plt.show()

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
for ax, (nombre, y_pred, color) in zip(axes, modelos_pred):
    residuos = y_test_reg - y_pred
    ax.scatter(y_pred, residuos, alpha=0.4, s=20, color=color)
    ax.axhline(0, color='red', ls='--', lw=1.5)
    ax.set_xlabel('Valor predicho (%)'); ax.set_ylabel('Residuo (%)')
    ax.set_title(nombre, fontweight='bold'); ax.grid(alpha=0.3)
fig.suptitle('Distribucion de residuos - modelos de regresion', fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig(RUTA_FIGS + '15_reg_residuos.png', dpi=150, bbox_inches='tight')
plt.show()

# Importancia de variables (MDI) del Random Forest
fig, ax = plt.subplots(figsize=(9, 6))
imp_top = imp_rf.head(12)
ax.barh(imp_top['Feature'][::-1], imp_top['Importancia'][::-1], color='darkorange', alpha=0.8)
ax.set_xlabel('Importancia (Mean Decrease Impurity)')
ax.set_title('Importancia de variables - Random Forest regresor', fontweight='bold')
ax.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.savefig(RUTA_FIGS + '16_rf_importancia.png', dpi=150, bbox_inches='tight')
plt.show()

# ---- Celda 14: SHAP del regresor (XGBoost) ----
explainer_xgb = shap.TreeExplainer(xgb_reg)
shap_vals_xgb = explainer_xgb.shap_values(X_test)
plt.figure(figsize=(10, 6))
shap.summary_plot(shap_vals_xgb, X_test, feature_names=FEATURES, show=False, plot_size=(10, 6))
plt.title('SHAP Summary Plot - XGBoost regresor', fontweight='bold', pad=15)
plt.tight_layout()
plt.savefig(RUTA_FIGS + '18_shap_xgb.png', dpi=150, bbox_inches='tight')
plt.show()

# =========================================================
# FASE 3: CLASIFICACIÓN
# =========================================================
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                             roc_auc_score, confusion_matrix, ConfusionMatrixDisplay,
                             RocCurveDisplay, precision_recall_curve)

THR = 0.55  # umbral de decisión optimizado en validación

def metricas_clasificacion(y_true, y_pred, y_prob, nombre=''):
    out = {'Accuracy': accuracy_score(y_true, y_pred),
           'Precision': precision_score(y_true, y_pred),
           'Recall': recall_score(y_true, y_pred),
           'F1': f1_score(y_true, y_pred),
           'ROC-AUC': roc_auc_score(y_true, y_prob)}
    if nombre:
        print(f"\n{nombre}: Acc={out['Accuracy']:.4f}  Prec={out['Precision']:.4f}  "
              f"Rec={out['Recall']:.4f}  F1={out['F1']:.4f}  AUC={out['ROC-AUC']:.4f}")
    return out

# ---- Celda 15: Logistic Regression (umbral 0.55) ----
lr_clf = LogisticRegression(class_weight='balanced', max_iter=1000, random_state=RANDOM_STATE)
lr_clf.fit(X_train_sc, y_train_clf)
y_prob_lr_clf = lr_clf.predict_proba(X_test_sc)[:, 1]
y_pred_lr_clf = (y_prob_lr_clf >= THR).astype(int)
res_lr_clf = metricas_clasificacion(y_test_clf, y_pred_lr_clf, y_prob_lr_clf, 'Logistic Regression - TEST')

# ---- Celda 16: Random Forest classifier ----
rf_clf = RandomForestClassifier(n_estimators=300, min_samples_leaf=5, max_features='sqrt',
                                class_weight='balanced', random_state=RANDOM_STATE, n_jobs=-1)
rf_clf.fit(X_train, y_train_clf)
y_prob_rf_clf = rf_clf.predict_proba(X_test)[:, 1]
y_pred_rf_clf = rf_clf.predict(X_test)
res_rf_clf = metricas_clasificacion(y_test_clf, y_pred_rf_clf, y_prob_rf_clf, 'Random Forest - TEST')

# ---- Celda 17: comparativa + matrices de confusión + ROC ----
res_clf = pd.DataFrame({
    'Modelo': ['Logistic Regression', 'Random Forest'],
    'Accuracy':  [res_lr_clf['Accuracy'],  res_rf_clf['Accuracy']],
    'Precision': [res_lr_clf['Precision'], res_rf_clf['Precision']],
    'Recall':    [res_lr_clf['Recall'],    res_rf_clf['Recall']],
    'F1':        [res_lr_clf['F1'],        res_rf_clf['F1']],
    'ROC-AUC':   [res_lr_clf['ROC-AUC'],   res_rf_clf['ROC-AUC']],
})
print(res_clf.to_string(index=False))

fig, axes = plt.subplots(1, 2, figsize=(11, 4))
for ax, (nombre, y_pred) in zip(axes, [('Logistic Regression', y_pred_lr_clf), ('Random Forest', y_pred_rf_clf)]):
    cm = confusion_matrix(y_test_clf, y_pred)
    ConfusionMatrixDisplay(cm, display_labels=['No supera', 'Supera']).plot(ax=ax, colorbar=False, cmap='Blues')
    ax.set_title(nombre, fontweight='bold')
fig.suptitle('Matrices de confusion - modelos de clasificacion', fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig(RUTA_FIGS + '19_matrices_confusion.png', dpi=150, bbox_inches='tight')
plt.show()

fig, ax = plt.subplots(figsize=(7, 6))
RocCurveDisplay.from_predictions(y_test_clf, y_prob_lr_clf,
                                 name=f"Logistic Regression (AUC={res_lr_clf['ROC-AUC']:.3f})", color='steelblue', ax=ax)
RocCurveDisplay.from_predictions(y_test_clf, y_prob_rf_clf,
                                 name=f"Random Forest (AUC={res_rf_clf['ROC-AUC']:.3f})", color='darkorange', ax=ax)
ax.plot([0, 1], [0, 1], 'k--', lw=1)
ax.set_title('Curvas ROC - modelos de clasificacion', fontweight='bold'); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(RUTA_FIGS + '20_curvas_roc.png', dpi=150, bbox_inches='tight')
plt.show()

# ---- Celda 18: SHAP del clasificador (regresión logística) ----
explainer_lr = shap.LinearExplainer(lr_clf, X_train_sc)
shap_vals_lr = explainer_lr.shap_values(X_test_sc)
plt.figure(figsize=(10, 6))
shap.summary_plot(shap_vals_lr, X_test_sc, feature_names=FEATURES, show=False, plot_size=(10, 6))
plt.title('SHAP Summary Plot - Logistic Regression (clasificador)', fontweight='bold', pad=15)
plt.tight_layout()
plt.savefig(RUTA_FIGS + '21_shap_logistica_clf.png', dpi=150, bbox_inches='tight')
plt.show()

# ---- Celda 19: curva de umbral (precision-recall-F1) ----
prec_arr, rec_arr, thresh_arr = precision_recall_curve(y_test_clf, y_prob_lr_clf)
f1_arr = 2 * prec_arr * rec_arr / (prec_arr + rec_arr + 1e-8)
idx_f1 = np.argmax(f1_arr[:-1])
print(f"Umbral optimo F1: {thresh_arr[idx_f1]:.3f} -> "
      f"Precision={prec_arr[idx_f1]:.3f}  Recall={rec_arr[idx_f1]:.3f}  F1={f1_arr[idx_f1]:.3f}")
print(f"Umbral aplicado ({THR}): Precision={res_lr_clf['Precision']:.3f}  "
      f"Recall={res_lr_clf['Recall']:.3f}  F1={res_lr_clf['F1']:.3f}")

fig, ax = plt.subplots(figsize=(7, 5))
ax.plot(thresh_arr, prec_arr[:-1], label='Precision', color='steelblue')
ax.plot(thresh_arr, rec_arr[:-1],  label='Recall',    color='darkorange')
ax.plot(thresh_arr, f1_arr[:-1],   label='F1',        color='seagreen', lw=2)
ax.axvline(THR, color='gray', ls='--', alpha=0.7, label=f'Umbral aplicado ({THR})')
ax.set_xlabel('Umbral'); ax.set_ylabel('Score')
ax.set_title('Precision, recall y F1 segun el umbral - Logistic Regression', fontweight='bold')
ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(RUTA_FIGS + '22_threshold_curve.png', dpi=150, bbox_inches='tight')
plt.show()

# =========================================================
# FASE 4: ABLACIÓN Y RANKING DE IMPORTANCIA
# =========================================================

# ---- Celda 20: estudio de ablación ----
grupos = {
    'Linea base (todas)':       FEATURES,
    'Sin llamadas_por_gestor':  [f for f in FEATURES if f != 'llamadas_por_gestor'],
    'Sin ASA_min':              [f for f in FEATURES if f != 'ASA_min'],
    'Sin top-3':                [f for f in FEATURES if f not in ['llamadas_por_gestor', 'ASA_min', 'TMO_min']],
    'Solo top-3':               ['llamadas_por_gestor', 'ASA_min', 'TMO_min'],
}

print(f"{'Configuracion':<28} {'R2':>7} {'RMSE':>7} {'F1':>7} {'AUC':>7}")
for nombre, feats in grupos.items():
    r = RidgeCV(alphas=np.logspace(-3, 3, 100), cv=TSCV).fit(X_train_sc[feats], y_train_reg)
    yp_r = r.predict(X_test_sc[feats])
    r2   = r2_score(y_test_reg, yp_r)
    rmse = np.sqrt(mean_squared_error(y_test_reg, yp_r))
    c = LogisticRegression(class_weight='balanced', max_iter=1000, random_state=RANDOM_STATE).fit(X_train_sc[feats], y_train_clf)
    prob_c = c.predict_proba(X_test_sc[feats])[:, 1]
    pred_c = (prob_c >= THR).astype(int)
    f1  = f1_score(y_test_clf, pred_c)
    auc = roc_auc_score(y_test_clf, prob_c)
    print(f"{nombre:<28} {r2:>7.3f} {rmse:>7.3f} {f1:>7.3f} {auc:>7.3f}")

# ---- Celda 21: ranking de importancia por método ----
imp_ridge       = pd.Series(np.abs(ridge.coef_),    index=FEATURES).sort_values(ascending=False)
imp_lr_clf      = pd.Series(np.abs(lr_clf.coef_[0]), index=FEATURES).sort_values(ascending=False)
imp_rf_reg      = pd.Series(rf.feature_importances_, index=FEATURES).sort_values(ascending=False)
imp_shap_xgb    = pd.Series(np.abs(shap_vals_xgb).mean(axis=0), index=FEATURES).sort_values(ascending=False)
imp_shap_lr_clf = pd.Series(np.abs(shap_vals_lr).mean(axis=0), index=FEATURES).sort_values(ascending=False)

metodos = {'Ridge': imp_ridge, 'Logistic': imp_lr_clf, 'RF (MDI)': imp_rf_reg,
           'SHAP XGB': imp_shap_xgb, 'SHAP LR': imp_shap_lr_clf}
ranking = pd.DataFrame({
    nombre: pd.Series({feat: i + 1 for i, feat in enumerate(imp.index)})
    for nombre, imp in metodos.items()
})
ranking['Rank_medio'] = ranking.mean(axis=1).round(2)
ranking = ranking.sort_values('Rank_medio')
print(ranking.to_string())